Repository NetDiver-OSS/NetAM, pull requests merged in 2020-10, with the labels that each got.

#17 ci: setup workflow for sonarcloud
  .github/workflows/danger.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .gitlab-ci.yml
  .gitlab/ci/_init.yml
  .gitlab/ci/package.yml
  .gitlab/ci/report.yml
  .gitlab/ci/test.yml
  .gitlab/ci/verify.yml
  renovate.json
  sonar-project.properties
Labels: Priority::1

#16 fix: update color scheme for section view
  app/controllers/sections_controller.rb
  app/helpers/usages_helper.rb
  app/views/sections/show.html.haml
  changelog/unreleased/update-color-scheme-for-section-view.yml
  spec/helpers/usages_helper_spec.rb
Labels: Priority::3, feature::enhancement

#26 Slack Notifications
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/sections_controller.rb
  app/jobs/scan_network_with_ping_job.rb
  app/models/section.rb
  app/services/base_service.rb
  app/services/notifications/send_service.rb
  app/services/notifications/slack/send_service.rb
  app/views/sections/_form.html.haml
  changelog/unreleased/add-slack-notification-after-scan.yml
  config/initializers/sidekiq_scheduler.rb
  config/netam.yml
  db/migrate/20201010180118_rails_settings_migration.rb
  spec/services/notifications/slack/send_service_spec.rb
  spec/simplecov_env.rb
Labels: feature::new

#44 feat: display last datetime scan on section
  Gemfile
  Gemfile.lock
  app/jobs/application_job.rb
  app/views/sections/show.html.haml
  changelog/unreleased/display-last-datetime-scan-on-section.yml
  lib/netam/section.rb
  locale/netam.pot
  spec/simplecov_env.rb
Labels: feature::new

#52 refactor: simplify dark mode class switcher
  app/helpers/application_helper.rb
  app/views/account/two_factor_auths/_recovery_code.html.haml
  app/views/account/two_factor_auths/_validate_topt.html.haml
  app/views/account/two_factor_auths/index.html.haml
  app/views/admin/backups/index.html.haml
  app/views/admin/jobs/index.html.haml
  app/views/admin/users/_form.html.haml
  app/views/admin/users/edit.html.haml
  app/views/admin/users/new.html.haml
  app/views/admin/users/show.html.haml
  app/views/application/index.html.haml
  app/views/devise/registrations/edit.html.haml
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/layouts/application.html.haml
  app/views/layouts/parts/_footer.html.haml
  app/views/layouts/parts/_navbar.html.haml
  app/views/permissions/_form.html.haml
  app/views/permissions/_rbac.html.haml
  app/views/permissions/edit.html.haml
  app/views/permissions/new.html.haml
  app/views/sections/_form.html.haml
  app/views/sections/edit.html.haml
  app/views/sections/new.html.haml
  app/views/sections/show.html.haml
  app/views/sections/status/_notification.html.haml
  app/views/setup/_form.html.haml
  app/views/setup/install.html.haml
  app/views/usages/_form.html.haml
  app/views/usages/edit.html.haml
  app/views/usages/new.html.haml
  app/views/utils/_form.html.haml
  app/views/utils/calculator.html.haml
  app/views/vlans/_form.html.haml
  app/views/vlans/edit.html.haml
  app/views/vlans/new.html.haml
  app/views/vlans/show.html.haml
  changelog/unreleased/simplify-dark-mode-class-switcher.yml
Labels: need-review, pr-failed

#53 feat: display workers status in homepage
  app/controllers/application_controller.rb
  app/views/application/index.html.haml
  changelog/unreleased/display-workers-status-in-homepage.yml
  spec/requests/usages_request_spec.rb
Labels: feature::new

#54 feat: add logger
  Gemfile
  Gemfile.lock
  README.md
  app/views/application/index.html.haml
  changelog/unreleased/add-customn-log-appenders.yml
  config/initializers/logger_appender.rb
  config/puma.rb
Labels: feature::new

#56 fix: display log on console
  config/initializers/logger_appender.rb
Labels: bug

#64 fix: update identifier field for usages
  changelog/unreleased/update-identifier-field-for-usages.yml
  db/migrate/20201019175343_update_identifier_for_usages.rb
Labels: bug

#66 fix: setup max-retry on backup worker
  app/workers/backup_database_worker.rb
  changelog/unreleased/setup-max-retry-on-backup-worker.yml
Labels: bug

#65 fix: add postgresql-client to docker image
  Dockerfile
  changelog/unreleased/add-postgresql-client-to-docker-image.yml
Labels: bug

#68 fix: split upsert with FQDN to avoid error on import
  .rubocop_todo.yml
  app/jobs/scan_network_with_ping_job.rb
  changelog/unreleased/split-upsert-with-fqdn-to-avoid-error-on-import.yml
Labels: bug

#67 feat: add MSTeams notifications
  Gemfile
  Gemfile.lock
  app/services/notifications/msteams/send_service.rb
  app/services/notifications/send_service.rb
  changelog/unreleased/add-msteams-notifications.yml
  config/netam.yml
  spec/services/notifications/msteams/send_service_spec.rb
Labels: feature::new

#84 feat: mail notifications
  README.md
  app/services/notifications/mail/send_service.rb
  app/services/notifications/send_service.rb
  changelog/unreleased/add-mail-notifications.yml
  config/netam.yml
  spec/simplecov_env.rb
Labels: feature::new

#69 fix: don't use cache on docker build
  .github/workflows/release.yml
Labels: bug

#85 refactor: optimize routes definition
  app/controllers/api/v1/base.rb
  app/controllers/api/v1/defaults.rb
  app/views/admin/jobs/index.html.haml
  app/views/layouts/parts/_navbar.html.haml
  app/views/usages/_import.html.haml
  changelog/unreleased/optimize-routes-definition.yml
  config/routes.rb
  spec/requests/jobs_controller_spec.rb
  spec/requests/usages_request_spec.rb
  spec/requests/utils_controller_spec.rb
Labels: feature::enhancement

#88 refactor: clean model validation
  app/models/permission.rb
  app/models/section.rb
  app/models/usage.rb
  app/models/user.rb
  app/models/vlan.rb
  changelog/unreleased/clean-model-validation.yml
  spec/lib/netam/scanner_spec.rb
  spec/requests/sections_request_spec.rb
  spec/requests/usages_request_spec.rb
Labels: feature::enhancement
