Repository NetDiver-OSS/NetAM, pull requests merged in 2020-12, with the labels that each got.

#170 Update cron job queue when worker configuration is updated
  app/models/section.rb
  app/models/worker.rb
  changelog/unreleased/update-cron-job-queue-when-worker-configuration-is-updated.yml
  spec/models/worker_spec.rb
Labels: bug

#150 Feat/tools devices list
  .rubocop_todo.yml
  app/controllers/api/v1/base.rb
  app/controllers/api/v1/device_types.rb
  app/controllers/api/v1/devices.rb
  app/controllers/device_types_controller.rb
  app/controllers/devices_controller.rb
  app/controllers/usages_controller.rb
  app/models/ability.rb
  app/models/device.rb
  app/models/device_type.rb
  app/models/usage.rb
  app/serializers/device_serializer.rb
  app/serializers/device_type_serializer.rb
  app/views/device_types/_form.html.haml
  app/views/device_types/edit.html.haml
  app/views/device_types/index.html.haml
  app/views/device_types/new.html.haml
  app/views/devices/_form.html.haml
  app/views/devices/edit.html.haml
  app/views/devices/index.html.haml
  app/views/devices/new.html.haml
  app/views/layouts/parts/_navbar.html.haml
  app/views/usages/_form.html.haml
  changelog/unreleased/add-devices-assignment-from-usages.yml
  config/routes.rb
  db/migrate/20201121214655_create_devices.rb
  db/migrate/20201121220540_create_devices_type.rb
  db/migrate/20201121220930_add_ref_devices_type_to_devices.rb
  db/migrate/20201121222109_add_ref_devices_to_usages.rb
  db/migrate/20201124211945_create_default_devices_types.rb
  locale/netam.pot
  spec/factories/device_types.rb
  spec/factories/devices.rb
  spec/requests/api/v1/device_types_request_spec.rb
  spec/requests/api/v1/devices_request_spec.rb
  spec/requests/device_types_request_spec.rb
  spec/requests/devices_request_spec.rb
  spec/requests/usages_request_spec.rb
Labels: feature::new

#183 Use correct field to generate identifier
  app/models/usage.rb
  changelog/unreleased/use-correct-field-to-generate-usage-identifier.yml
  spec/models/usage_spec.rb
Labels: Priority::1, bug

#178 Setup codeql
  .github/workflows/codeql-analysis.yml
Labels: technical debt

#208 Launch identifier calculation before_validation instead of after_initialize
  app/models/usage.rb
  changelog/unreleased/launch-identifier-calculation-before_validation-instead-of-after_initi.yml
  spec/models/usage_spec.rb
Labels: bug

#213 fix: sanitize action to allow scan on section view
  app/views/layouts/parts/_actions.html.haml
  changelog/unreleased/scan-action-on-section-view.yml
Labels: bug
