Repository NetDiver-OSS/NetAM, pull requests merged in 2020-11, with the labels that each got.

#99 fix: setup route changes
  app/controllers/application_controller.rb
  app/views/setup/_form.html.haml
Labels: bug

#94 Use pull request shortcut for GitHub instead of GitLab
  CHANGELOG.md
  bin/generate_changelog
Labels: bug

#95 IP request
  app/controllers/api/v1/sections.rb
  app/controllers/application_controller.rb
  app/javascript/components/section/request_ip.vue
  app/javascript/packs/application.js
  app/models/section.rb
  app/views/layouts/application.html.haml
  app/views/layouts/parts/_actions.html.haml
  app/views/sections/show.html.haml
  app/views/usages/_form.html.haml
  changelog/unreleased/use-api-endpoint-to-request-ip-address-and-display-it-in-modal.yml
  config/webpack/environment.js
  config/webpack/loaders/vue.js
  config/webpacker.yml
  package.json
  spec/requests/api/v1/sections_request_spec.rb
  yarn.lock
Labels: feature::new

#96 debt
  app/controllers/api/v1/sections.rb
  app/jobs/export_section_to_csv_job.rb
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
Labels: technical debt

#101 Feat/dark theme js
  app/javascript/components/section/request_ip.vue
  app/javascript/packs/application.js
  package.json
  yarn.lock
Labels: bug

#104 Feat/translate js
  .github/workflows/main.yml
  .gitignore
  Dockerfile
  app/assets/config/manifest.js
  app/assets/javascripts/application.js
  app/javascript/components/section/request_ip.vue
  app/views/layouts/application.html.haml
  config/initializers/gettext_i18n_rails_js.rb
  lib/tasks/gettext.rake
  locale/netam.pot
Labels: bug, feature::new

#110 Add i18n for devise
  Gemfile
  Gemfile.lock
Labels: traduction

#113 fix: get unused ip return full ip list on full filled range
  app/controllers/api/v1/sections.rb
  app/javascript/components/section/request_ip.vue
  app/models/section.rb
  changelog/unreleased/get-unused-ip-return-clean-error-when-range-is-full.yml
Labels: bug

#114 Use netam lib to calculate free IP
  app/controllers/sections_controller.rb
  app/views/sections/index.html.haml
  app/views/sections/show.html.haml
  changelog/unreleased/use-right-calculation-method-to-get-free-ip-on-section.yml
  lib/netam/network/range.rb
Labels: bug

#116 feat(export): uniformize export with import format
  app/jobs/export_section_to_csv_job.rb
  changelog/unreleased/uniformize-export-with-import-format.yml
  spec/jobs/export_section_to_csv_job_spec.rb
Labels: feature::enhancement

#117 fix: add missing translation string
  app/views/usages/_form.html.haml
  app/views/usages/_import.html.haml
  locale/netam.pot
Labels: bug, traduction

#102 New Crowdin updates
  locale/de/netam.po
  locale/es/netam.po
  locale/fr/netam.po
  locale/it/netam.po
Labels: traduction

#121 Docs/rework readme
  README.md
Labels: documentation

#125 Don't translate database state
  app/views/usages/_form.html.haml
  changelog/unreleased/don-t-translate-database-state.yml
  locale/netam.pot
Labels: bug, traduction

#51 add worker management
  .github/workflows/main.yml
  .rubocop_todo.yml
  app/assets/stylesheets/application.css
  app/controllers/admin/sidekiq_controller.rb
  app/controllers/admin/workers_controller.rb
  app/controllers/api/v1/sections.rb
  app/controllers/application_controller.rb
  app/controllers/sections_controller.rb
  app/javascript/packs/select.js
  app/models/section.rb
  app/models/worker.rb
  app/views/admin/sidekiq/index.html.haml
  app/views/admin/workers/_form.html.haml
  app/views/admin/workers/edit.html.haml
  app/views/admin/workers/index.html.haml
  app/views/admin/workers/new.html.haml
  app/views/application/index.html.haml
  app/views/layouts/parts/_navbar.html.haml
  app/workers/concerns/status_expiration.rb
  app/workers/scan_network_with_ping_worker.rb
  changelog/unreleased/add-sidekiq-link-into-admin-menu.yml
  changelog/unreleased/add-worker-management-interface.yml
  changelog/unreleased/split-load-between-workers.yml
  config/routes.rb
  db/migrate/20201017005215_create_workers.rb
  db/migrate/20201017092726_add_worker_ref_to_sections.rb
  docker-compose.worker.yml
  lib/netam/scanner.rb
  locale/netam.pot
  spec/jobs/scan_network_with_ping_job_spec.rb
  spec/lib/netam/scanner_spec.rb
  spec/requests/jobs_controller_spec.rb
  spec/requests/sections_request_spec.rb
  spec/requests/workers_spec.rb
  spec/workers/scan_network_with_ping_worker_spec.rb
Labels: feature::new

#127 fix: affect sections on worker creation
  app/controllers/admin/workers_controller.rb
Labels: bug

#134 Setup factoryBot for tests
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  spec/factories/sections.rb
  spec/factories/sequences.rb
  spec/factories/users.rb
  spec/factories/vlans.rb
  spec/helpers/usages_helper_spec.rb
  spec/jobs/export_section_to_csv_job_spec.rb
  spec/jobs/scan_address_with_ping_job_spec.rb
  spec/lib/backup/helper_spec.rb
  spec/lib/backup/manager_spec.rb
  spec/lib/netam/network/dns_spec.rb
  spec/lib/netam/network/range_spec.rb
  spec/lib/netam/scanner_spec.rb
  spec/lib/netam/utils/ip_calculator_spec.rb
  spec/mailers/application_spec.rb
  spec/mailers/previews/application_preview.rb
  spec/models/permission_spec.rb
  spec/models/section_spec.rb
  spec/models/user_spec.rb
  spec/models/vlan_spec.rb
  spec/rails_helper.rb
  spec/requests/account/two_factor_auths_spec.rb
  spec/requests/admin/backups_request_spec.rb
  spec/requests/admin/users_request_spec.rb
  spec/requests/api/v1/backups_request_spec.rb
  spec/requests/api/v1/sections_request_spec.rb
  spec/requests/api/v1/vlans_request_spec.rb
  spec/requests/application_request_spec.rb
  spec/requests/jobs_controller_spec.rb
  spec/requests/permissions_request_spec.rb
  spec/requests/sections_request_spec.rb
  spec/requests/usages_request_spec.rb
  spec/requests/utils_controller_spec.rb
  spec/requests/vlans_spec.rb
  spec/requests/workers_spec.rb
  spec/services/notifications/msteams/send_service_spec.rb
  spec/services/notifications/slack/send_service_spec.rb
  spec/workers/backup_database_worker_spec.rb
  spec/workers/scan_network_with_ping_worker_spec.rb
Labels: technical debt

#136 feat: worker displaying in section show
  app/assets/stylesheets/application.css
  app/models/section.rb
  app/models/worker.rb
  app/views/sections/show.html.haml
  changelog/unreleased/add-affected-worker-display-in-section-show.yml
  config/initializers/gettext_i18n_rails_js.rb
  locale/netam.pot
Labels: feature::new

#138 Delete unused html
  app/views/admin/workers/index.html.haml
Labels: bug

#142 feat: insert OUI file into database
  app/models/mac_address.rb
  app/workers/ingest_oui_database_worker.rb
  db/migrate/20201119222129_add_mac_addresses_table.rb
  spec/fixtures/oui.txt
  spec/workers/ingest_oui_database_worker_spec.rb
Labels: feature::new

#140 Feat/part/download mac address database
  app/workers/load_mac_address_table_worker.rb
  spec/workers/load_mac_address_table_worker_spec.rb
Labels: feature::new

#143 Schedule OUI database update
  config/initializers/sidekiq_scheduler.rb
  config/schedule.yml
Labels: feature::new

#141 Add: spain flag
  lib/netam/translation.rb
  public/flags/4x3/es.svg
Labels: feature::enhancement

#145 add: front interface for mac vendor lookup
  app/controllers/utils_controller.rb
  app/views/layouts/parts/_navbar.html.haml
  app/views/utils/_formvendor.html.haml
  app/views/utils/mac_vendor.html.haml
  config/routes.rb
  spec/requests/utils_controller_spec.rb
Labels: feature::new

#139 add: changelog for mac address vendor lookup
  app/controllers/utils_controller.rb
  app/models/mac_address.rb
  app/views/layouts/parts/_navbar.html.haml
  app/views/sections/show.html.haml
  app/views/utils/_formvendor.html.haml
  app/views/utils/calculator.html.haml
  app/views/utils/mac_vendor.html.haml
  app/workers/ingest_oui_database_worker.rb
  app/workers/load_mac_address_table_worker.rb
  changelog/unreleased/add-mac-address-vendor-lookup-utils.yml
  config/initializers/sidekiq_scheduler.rb
  config/routes.rb
  config/schedule.yml
  db/migrate/20201119222129_add_mac_addresses_table.rb
  locale/netam.pot
  spec/fixtures/oui.txt
  spec/requests/utils_controller_spec.rb
  spec/workers/ingest_oui_database_worker_spec.rb
  spec/workers/load_mac_address_table_worker_spec.rb
Labels: feature::new

#163 upgrade simplecov for sonarcloud
  .github/workflows/main.yml
  Gemfile
  Gemfile.lock
  sonar-project.properties
  spec/simplecov_env.rb
Labels: bug, technical debt

#166 Allow before actions on update action for sections
  app/controllers/sections_controller.rb
  changelog/unreleased/allow-before-actions-on-update-action-for-sections.yml
Labels: bug
