Repository NetDiver-OSS/NetAM, pull requests merged in 2021-01, with the labels that each got.

#226 Use same method to cache gem in Github Action
  .github/workflows/main.yml
  .github/workflows/rubocop-analysis.yml
Labels: github_actions, suggestion

#218 Clean rubocop warning
  Gemfile.lock
  config/initializers/gettext_i18n_rails_js.rb
  db/migrate/20200321202715_change_usages_status_default_value.rb
Labels: ruby, suggestion

#236 Fix/dependabot AIO
  Gemfile
  Gemfile.lock
  package.json
  yarn.lock
Labels: dependencies

#237 Pagination
  Gemfile
  Gemfile.lock
  app/controllers/admin/users_controller.rb
  app/controllers/admin/workers_controller.rb
  app/controllers/device_types_controller.rb
  app/controllers/devices_controller.rb
  app/controllers/sections_controller.rb
  app/controllers/vlans_controller.rb
  app/views/admin/users/index.html.haml
  app/views/admin/workers/index.html.haml
  app/views/device_types/index.html.haml
  app/views/devices/index.html.haml
  app/views/kaminari/_first_page.html.erb
  app/views/kaminari/_gap.html.erb
  app/views/kaminari/_last_page.html.erb
  app/views/kaminari/_next_page.html.erb
  app/views/kaminari/_page.html.erb
  app/views/kaminari/_paginator.html.erb
  app/views/kaminari/_prev_page.html.erb
  app/views/sections/index.html.haml
  app/views/vlans/index.html.haml
  changelog/unreleased/replace-javascript-datatable-pagination-with-real-pagination-gem.yml
  config/initializers/kaminari_config.rb
Labels: feature::enhancement, ruby

#247 fix: highchart design
  app/javascript/components/section/pie_usage.vue
Labels: feature::enhancement

#248 feat: tabs in section
  app/javascript/components/section/tabs.vue
  app/javascript/components/tab.vue
  app/javascript/packs/application.js
  app/views/sections/show.html.haml
Labels: feature::enhancement

#258 UI: Increase slide speed
  app/javascript/components/slide_menu.vue
Labels: feature::enhancement, javascript

#252 Setup docker image deployment to github registry
  .github/workflows/docker.yml
Labels: docker, feature::enhancement
