Repository NetDiver-OSS/NetAM, pull requests merged in 2021-03, with the labels that each got.

#307 Restrict folder copied into Docker image
  .dockerignore
Labels: docker, feature::enhancement

#301 Upgrade to ruby 3.0.0
  .github/workflows/crowdin.yml
  .github/workflows/main.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  app/controllers/account/two_factor_auths_controller.rb
  changelog/unreleased/upgrade-to-ruby-3-0-0.yml
  config/initializers/doorkeeper.rb
Labels: dependencies, ruby

#349 feat: add tools for PTR resolution
  app/controllers/utils_controller.rb
  app/views/layouts/_navbar.html.haml
  app/views/utils/_formptrresolution.html.haml
  app/views/utils/ptr_resolution.html.haml
  changelog/unreleased/add-tools-to-perform-unitary-ptr-resolution.yml
  config/routes.rb
  locale/netam.pot
Labels: feature::new

#350 feat: add tools network range splitter
  app/controllers/utils_controller.rb
  app/views/layouts/_navbar.html.haml
  app/views/utils/_formnetsplitter.html.haml
  app/views/utils/network_splitter.html.haml
  changelog/unreleased/add-tools-for-network-range-splitting.yml
  config/routes.rb
  locale/netam.pot
Labels: feature::new

#352 Display cron format validity dynamically on input
  app/javascript/components/section/cron_validator.vue
  app/javascript/packs/application.js
  app/javascript/stylesheets/application.scss
  app/views/sections/_form.html.haml
  changelog/unreleased/display-cron-format-validity-dynamically-on-input.yml
  package.json
  yarn.lock
Labels: feature::new, javascript

#353 fix: missing s to params in network_splitter
  app/controllers/utils_controller.rb
Labels: bug

#358 Display scan jobs on section page
  app/views/sections/show.html.haml
  changelog/unreleased/display-scan-jobs-on-section-page.yml
  lib/netam/section.rb
  locale/netam.pot
Labels: feature::new, ruby
