Repository NetDiver-OSS/NetAM, pull requests merged in 2021-04, with the labels that each got.

#355 feat: DNS resolver
  app/controllers/utils_controller.rb
  app/views/layouts/_navbar.html.haml
  app/views/utils/_formdnsresolver.html.haml
  app/views/utils/dns_resolver.html.haml
  changelog/unreleased/add-tools-to-perform-dns-resolution.yml
  config/routes.rb
  lib/netam/network/dns.rb
  lib/netam/utils/dns.rb
  locale/netam.pot
  spec/lib/netam/network/dns_spec.rb
  spec/requests/utils_controller_spec.rb
Labels: feature::new

#373 Persistent sidebar
  app/helpers/application_helper.rb
  app/javascript/components/search/search-bar.vue
  app/javascript/components/sidebar-menu.vue
  app/javascript/components/theme_switcher.vue
  app/javascript/packs/application.js
  app/javascript/stylesheets/application.scss
  app/views/layouts/_footer.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/_navbar.html.haml
  app/views/layouts/_sidebar.html.haml
  app/views/layouts/application.html.haml
Labels: feature::enhancement, ruby

#374 fix: sidekiq_scheduler to map to correct worker at reboot
  changelog/unreleased/correctly-assign-section-to-worker-for-scheduled-scan-at-reboot.yml
  config/initializers/sidekiq_scheduler.rb
Labels: bug

#376 feat: TypeSense reindexation and improvements
  .rubocop_todo.yml
  app/controllers/usages_controller.rb
  app/javascript/components/search/search-bar.vue
  app/javascript/components/search/search-item.vue
  app/javascript/components/search/search_query.js
  app/javascript/components/sidebar-menu.vue
  app/services/device_types/reindex_service.rb
  app/services/devices/reindex_service.rb
  app/services/rackspaces/reindex_service.rb
  app/services/sections/reindex_service.rb
  app/services/usages/create_service.rb
  app/services/usages/destroy_service.rb
  app/services/usages/reindex_service.rb
  app/services/usages/update_service.rb
  app/services/vlans/reindex_service.rb
  app/workers/reindex_typesense.rb
  app/workers/scan_network_worker.rb
  config/schedule.yml
Labels: feature::enhancement

#389 docs: add inline documentation
  .github/workflows/documentation.yml
  docs/CNAME
  docs/dev/admin/index.md
  docs/dev/api/index.md
  docs/dev/architecture/index.md
  docs/dev/index.md
  docs/dev/usage/index.md
  docs/index.md
  docs/license.md
  mkdocs-requirements.txt
  mkdocs.yml
Labels: documentation

#392 fix: rubocop alerts
  .rubocop_todo.yml
  app/services/usages/create_service.rb
  app/workers/scan_network_worker.rb
Labels: security

#393 Add description text to documentation
  Makefile
  docs/admin/index.md
  docs/api/index.md
  docs/architecture/index.md
  docs/configuration/index.md
  docs/dev/index.md
  docs/index.md
  docs/usage/index.md
  mkdocs.yml
Labels: documentation

#410 docs(usage): fix missings informations
  docs/usage/index.md
Labels: documentation
