Repository NetDiver-OSS/NetAM, pull requests merged in 2021-08, with the labels that each got.

#534 chore: upgrade brakeman version in CI
  .github/workflows/main.yml
Labels: bug, dependencies

#531 fix get_ip component
  app/javascript/components/section/request_ip.vue
  changelog/unreleased/delete-vue-fragment-who-cause-node-insert-failure-on-get_ip-component.yml
  package.json
  yarn.lock
Labels: bug, javascript

#538 docs: remove useless readme part
  README.md
Labels: documentation
